function [fitresult, gof] = createFit(Iin1a, Vin1a)
%CREATEFIT(IIN1A,VIN1A)
%  Create a fit.
%
%  Data for 'fit1' fit:
%      X Input : Iin1a
%      Y Output: Vin1a
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Feb-2019 20:32:10


%% Fit: 'fit1'.
[xData, yData] = prepareCurveData( Iin1a, Vin1a );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.705702661197567 6.34643652123576 -0.186410493305058 -956.908481910216];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'fit1' );
h = plot( fitresult, xData, yData );
legend( h, 'Experimental', 'Exponential Fit', 'Location', 'NorthEast' );
% Label axes
xlabel('Voltage (V)')
ylabel('Current (A)')
grid on


