function [fitresult, gof] = createFit1(Vin2_100, Vin2_1000,Vin2_10k, y1,L1,L2,L3)
%CREATEFIT1(VIN2_100,Y1)
%  Create a fit.
%
%  Data for 'fit2' fit:
%      X Input : Vin2_100
%      Y Output: y1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Feb-2019 22:34:34


%% Fit: 'fit2'.
[xData, yData] = prepareCurveData( Vin2_100, y1 );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'fit2' );
plot(Vin2_100,L1)
hold on
plot(Vin2_1000,L2)
plot(Vin2_10k,L3)
plot( fitresult );
legend('R=100 Ohm Resistor', 'R=1000 Ohm Resistor', 'R=10 kOhm Resistor','m = 38.74 1/V, b = -33.11 log(A)', 'Location', 'NorthEast' );
xlim([.3 1])
title('Current vs. Voltage for varied resistances')
% Label axes
xlabel('Voltage (V)')
ylabel('Current (log(A))')
grid on


